language: cpp
dist: xenial
compiler: gcc

addons: 
  apt: 
    packages: libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Wt
  - sudo apt-get install -qq witty witty-dbg witty-dev witty-doc
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs


services:
 - xvfb

script: 
  # Test
  - qmake -qt=qt5 ndsmake_test.pro
  - make debug
  - ./ndsmake_test
  # The program
  - qmake -qt=qt5 ndsmake.pro
  - make debug
  # - ./ndsmake ndsmake.pro # Do not run, gives an error
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
